USE NORTHWND;
--LẤY DS CÁC CUSTOMER CÓ REGION KHÔNG BỊ NULL
SELECT Region FROM Customers WHERE Region IS NOT NULL;
-- LẤY DS CÁC CUSTOMER KHÔNG CÓ TÊN CÔNG TY
SELECT * FROM Customers WHERE CompanyName IS NULL;
--LẤY RA ALL ĐƠN HÀNG CHƯA ĐƯỢC GIAO VÀ CÓ KHU VỰC GIAO KHÔNG BỊ NULL
SELECT * FROM Orders WHERE ShippedDate IS NULL AND ShipRegion IS NOT NULL;