-- LAY RA 5 DONG DAU TIEN TRONG BANG CUSTOMERS
USE NORTHWND; 
SELECT TOP 10 * FROM [dbo].[Customers];
--LAY RA 30% NHAN VIEN CUA CONG TY HIEN TAI	
SELECT TOP 30 PERCENT * FROM dbo.Customers;
--LAY RA CAC DON HANG CO MA KHACH KHONG DUOC TRUNG LAP VA CHI IN RA 5 DONG DAU TIEN
SELECT DISTINCT TOP 5 * FROM dbo.Orders;